FROM python:3.9-buster

WORKDIR /app

COPY ./ /app

RUN pip install --no-cache-dir -r /app/requirements.txt

WORKDIR /app/CrimeData

CMD ["celery", "-A", "celery_app:celery_app", "worker", "-l", "info"]